---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: S3400-48T6SP-snmp-exporter
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://prometheus-community.github.io/helm-charts
      chart: prometheus-snmp-exporter
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    fullnameOverride: S3400-48T6SP-snmp-exporter
    image:
      repository: quay.io/prometheus/snmp-exporter
    extraArgs:
      - "--config.file=/config/snmp.yaml"
    extraConfigmapMounts:
      - name: S3400-48T6SP-snmp-exporter
        mountPath: /config/snmp.yaml
        subPath: snmp.yaml
        configMap: S3400-48T6SP-snmp-exporter
        readOnly: true
        defaultMode: 420
    serviceMonitor:
      enabled: true
      params:
        - name: S3400-48T6SP
          target: 192.168.10.3
          module:
            - if_mib
      scrapeTimeout: 30s
#      scrapeInterval: 60s
      relabelings:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: S3400-48T6SP-snmp-exporter:9116
