---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./cilium/ks.yaml
  - ./coredns/ks.yaml
  - ./descheduler/ks.yaml
  - ./local-path-provisioner/ks.yaml
  - ./metrics-server/ks.yaml
  - ./nfs-client-provisioner/nfs-client-provisioner.yaml
  - ./reloader/ks.yaml
  - ./snapshot-controller/ks.yaml
