---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app democratic-csi
  namespace: storage
spec:
  interval: 30m
  chart:
    spec:
      chart: democratic-csi
      version: 0.13.7
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    csiDriver:
      # should be globally unique for a given cluster
      name: "org.democratic-csi.iscsi-synology"
    driver:
      existingConfigSecret: democratic-csi-secret
      image: docker.io/democraticcsi/democratic-csi:v1.8.3
      config:
        driver: synology-iscsi
    externalProvisioner:
      image: registry.k8s.io/sig-storage/csi-provisioner:v3.5.0
    externalResizer:
      image: registry.k8s.io/sig-storage/csi-resizer:v1.8.0
    externalSnapshotter:
      image: registry.k8s.io/sig-storage/csi-snapshotter:v6.2.2
    externalHealthMonitorController:
      enabled: true
      image: registry.k8s.io/sig-storage/csi-external-health-monitor-controller:v0.9.0
    csiProxy:
      image: docker.io/democraticcsi/csi-grpc-proxy:v0.5.3
    controller:
      resources:
        requests:
          cpu: 10m
          memory: 100Mi
        limits:
          memory: 200Mi
    node:
      cleanup:
        image: docker.io/busybox:1.36.1
      driver:
        image: docker.io/democraticcsi/democratic-csi:v1.8.3
        resources:
          requests:
            cpu: 15m
            memory: 150Mi
          limits:
            memory: 250Mi
      driverRegistrar:
        image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.8.0
      format:
        ext4:
        customOptions:
          - -E
          - nodiscard
    storageClasses:
      - name: synology-iscsi-retain
        defaultClass: false
        reclaimPolicy: Retain
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: ext4
        mountOptions: []
      - name: synology-iscsi-delete
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: ext4
        mountOptions: []
    volumeSnapshotClasses:
      - name: synology-iscsi
        parameters:
          lunSnapshotTemplate: |
            is_locked: true

            # https://kb.synology.com/en-me/DSM/tutorial/What_is_file_system_consistent_snapshot
            # Note that app consistent snapshots require a working Synology Storage Console. Otherwise both values will have
            # equivalent behavior.
            is_app_consistent: true
        secrets:
          snapshotter-secret:
