---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: home-assistant-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Home Assistant
        CAMERA_AUTH: "{{ .CAMERA_AUTH }}"
        HASS_TOKEN: "{{ .HASS_TOKEN }}"
        HASS_POSTGRES_URL: "postgresql://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASS }}@postgres-v15-rw.database.svc.cluster.local/home_assistant"
        LATITUDE: "{{ .HASS_LATITUDE }}"
        LONGITUDE: "{{ .HASS_LONGITUDE }}"
        SECURE_DEVICES_PIN: "{{ .SECURE_DEVICES_PIN }}"
        # Postgres Init
        POSTGRES_DB: home_assistant
        POSTGRES_HOST: postgres-v15-rw.database.svc.cluster.local
        POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        POSTGRES_USER: "{{ .POSTGRES_USER }}"
  dataFrom:
    - extract:
        key: home-assistant
    - extract:
        key: cloudnative-pg
