---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config-pvc.yaml
  - helm-release.yaml
  - home-assistant-secret.yaml
  - net-attach.yaml
  - volsync.yaml
  - volsync-local.yaml
labels:
  - pairs:
      app.kubernetes.io/name: home-assistant
      app.kubernetes.io/instance: home-assistant
