---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: hass-trusted
  namespace: home
spec:
  config: '{
        "cniVersion": "1.0.0",
        "type": "macvlan",
        "master": "eth0.1010",
        "mode": "bridge",
        "ipam": {
          "type": "static",
          "addresses": [
             {
               "address": "192.168.210.253/24"
             }
           ],
           "routes": [
              { "dst": "192.168.210.0/24", "gw": "192.168.210.1" }
           ]
        }
      }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: hass-cameras
  namespace: home
spec:
  config: '{
        "cniVersion": "1.0.0",
        "type": "macvlan",
        "master": "eth0.1024",
        "mode": "bridge",
        "ipam": {
          "type": "static",
          "addresses": [
             {
               "address": "10.249.250.202/24"
             }
           ],
           "routes": [
              { "dst": "10.249.250.0/24", "gw": "10.249.250.1" }
           ]
        }
      }'
