---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword-connect
  namespace: security
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect:8080
      vaults:
        k3s-vms-flux: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: op-credentials
            key: token
            namespace: security
