---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: ingress-nginx
      namespace: networking
  values:
    hajimari:
      title: Apps
      darkTheme: espresso
      alwaysTargetBlank: true
      showGreeting: false
      showAppGroups: false
      showAppStatus: false
      showBookmarkGroups: false
      showGlobalBookmarks: false
      showAppUrls: false
      defaultEnable: true
      namespaceSelector:
        matchNames:
          - default
          - home
          - media
          - monitoring
          - networking
          - rook-ceph
          - storage
      name: "Turtle"
      customApps:
        - group: Home
          apps:
            - name: pfsense
              url: http://192.168.10.1
              icon: wall-fire
            - name: Synology
              url: http://192.168.10.15:5000
              icon: test-tube
            - name: S3400-48T6SP
              url: http://192.168.10.3
              icon: switch
            - name: T1500G-10MPS
              url: http://192.168.10.20
              icon: switch
            - name: S3700-24T4F
              url: http://192.168.10.2
              icon: switch
            - name: Rook Internal
              url: https://192.168.10.102:8443/
              icon: switch
            - name: Grafana-DS
              url: https://grafana.davidstewen.com
            - name: Grafana-Blades
              url: https://192.168.10.151/
            - name: Gitops
              url: https://gitops.davidstewen.com/
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "false"
        hosts:
          - host: &host "hajimari.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podAnnotations:
      configmap.reloader.stakater.com/reload: hajimari-settings
    persistence:
      data:
        enabled: true
        type: emptyDir
    resources:
      requests:
        cpu: 100m
        memory: 128M
