---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unifi-backup
  namespace: home
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: unifi-backup-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        # UNIFI_USERNAME UNIFI_PASSWORD UNIFI_URL=https://ip:8443
        key: unifi-backup
