---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi-backup
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: cronjob
      cronjob:
        concurrencyPolicy: Forbid
        schedule: "@daily"

    restartPolicy: OnFailure

    image:
      repository: ghcr.io/johannrichard/unifi-backup/unifi-controller-backup
      tag: latest

    envFrom:
      - secretRef:
          name: unifi-backup-secret
    env:
      - name: BACKUP_LOCATION
        value: &path /backups
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"

    service:
      main:
        enabled: false

    persistence:
      backups:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_IP}"
            path: /mnt/biggie/backups/unifi
        mountPath: *path
        readOnly: false
