---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - externalsecret.yaml
labels:
  - pairs:
      app.kubernetes.io/name: unifi-backup
      app.kubernetes.io/instance: unifi-backup
