---
kubernetes:
  children:
    master:
      hosts:
        k3s-nvme1:
          ansible_user: dstewen
          ansible_host: 192.168.10.94
        k3s-nvme2:
          ansible_user: dstewen
          ansible_host: 192.168.10.95
        k3s-nvme3:
          ansible_user: dstewen
          ansible_host: 192.168.10.96
    worker:
      hosts:
        k3s-nvme4:
          ansible_user: dstewen
          ansible_host: 192.168.10.97
        k3s-nvme5:
          ansible_user: dstewen
          ansible_host: 192.168.10.98
        k3s-nvme6:
          ansible_user: dstewen
          ansible_host: 192.168.10.99
        nuc1:
          ansible_user: dstewen
          ansible_host: 192.168.10.100
          ceph_drives: /dev/disk/by-id/scsi-SATA_Samsung_SSD_860_S419NGAK201355E
        nuc3:
          ansible_user: dstewen
          ansible_host: 192.168.10.102
          ceph_drives: /dev/disk/by-id/scsi-SATA_Samsung_SSD_860_S3YANB0K230462F
        blade7:
          ansible_user: dstewen
          ansible_host: 192.168.10.37
          ceph_drives: /dev/disk/by-id/nvme-WD_Blue_SN570_500GB_220628800801
        blade8:
          ansible_user: dstewen
          ansible_host: 192.168.10.38
          ceph_drives: /dev/disk/by-id/nvme-WD_Blue_SN570_500GB_220628800737
