---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
#  - ./alertmanager/kustomization.yaml
  - ./grafana/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./kubernetes-dashboard/ks.yaml
  - ./loki/ks.yaml
#  - ./pihole-exporter/ks.yaml
  - ./prometheus-nut-exporter/ks.yaml
  - ./promtail/ks.yaml
  - ./smartctl-exporter/ks.yaml
  - ./snmp-exporter/ks.yaml
  - ./speedtest-exporter/speedtest-exporter.yaml
  - ./unpoller/ks.yaml
