---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/linuxserver/calibre
      tag: 6.23.0

#    podSecurityContext:
#      runAsUser: 568
#      runAsGroup: 568
#      fsGroup: 568
#      fsGroupChangePolicy: "OnRootMismatch"
#      supplementalGroups:
#        - 65539

    service:
      main:
        ports:
          http:
            port: 8080
      webserver:
        enabled: true
        ports:
          webserver:
            enabled: true
            port: 8081
            protocol: TCP
            targetPort: 8081
        type: ClusterIP

    env:
      TZ: ${TZ}
      PUID: "568"
      PGID: "65539"

#    probes:
#      liveness:
#        enabled: false
#      readiness:
#        enabled: false
#      startup:
#        enabled: false

    persistence:
      config:
        enabled: true
        existingClaim: calibre-config-0
      media:
        enabled: true
        existingClaim: media-nfs
        mountPath: /media

    ingress:
      main:
        primary: true
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNEL_ID}.cfargotunnel.com"
        hosts:
          - host: &host "calibre.${SECRET_DOMAIN_CASA}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: wildcard-tls

    resources:
      requests:
        cpu: 0.003
        memory: 1Gi
      limits:
        memory: 10Gi
