---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-workloads-plexautolanguages
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-workloads-rook-ceph-cluster
    - name: cluster-workloads-volsync
  path: ./k8s/cluster-0/workloads/media/plexautolanguages/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: plexautolanguages
      namespace: media
  interval: 30m
  retryInterval: 1m
  timeout: 3m
