---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-mailqtt
  namespace: flux-system
spec:
  path: ./kubernetes/apps/home/mailqtt/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: mailqtt
      namespace: home
  interval: 30m
  retryInterval: 1m
  timeout: 3m
