apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:phYWYsWVPvgw4C8k8julldTkZf4o7Dc+wwY/DA1IY0z7AiqYDjNJ8Q==,iv:DkinLey4BHZv49h80+cddflFhCW3v6uzTUo28+FycJY=,tag:MU2D9mtCeeDzILt+ItzdfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbTA3NzBQbXN6dktWMmF3
            aVVMMFg2aytGUDFaNzJwRFo1ekYzNjhZb3lNCi8xb0RoMXlXQWVxVWdvQ0Zjak83
            aUJZbnZpQWxqSmlWUnVPTzlLWXFUQmcKLS0tIFk5WWIwcVJJOXV4a3B4Tm5ncE1n
            SEdseU1GcTVmc0tyaEZBTDdjQnJVb2MKpWieRj8SE1aXxA9Oa+oy7wzRE+bwwQ5f
            FeIENIF91+xTCC1ldl1laOwRKocLLJkPN70GOsYt8Pg7cLM8QwHA7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-14T10:15:25Z"
    mac: ENC[AES256_GCM,data:FWXfmlNgx23jr1FqPdnishTRrXejXRQxDTRSV8vo72XrKR33k4GFoFf43PfmjKseOKF1fFCpd9mRPWergAsIZHeKt7mqDYBVg8pkHscw8WWjgaCpBT38MionlgulnhGjfm/vOurUCYVRr9nJ1ucbWXcL1BtAHd9gsRV9M96KFVE=,iv:p1JDc9jtN8ecTrqkRGCZoXn+znGzNmC+T6YKSx8Qqvg=,tag:OqSIBT2vDWGmiy3b5TaMww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
