---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config-0
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
