---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
configMapGenerator:
  - name: bazarr-sub-cleaner-cm
    files:
      - sub-cleaner.sh
generatorOptions:
  disableNameSuffixHash: true
resources:
  - config-pvc.yaml
  - helm-release.yaml
  - volsync.yaml
  - volsync-local.yaml
labels:
  - pairs:
      app.kubernetes.io/name: bazarr
      app.kubernetes.io/instance: bazarr
