apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:FNg=,iv:tcjVtGmP0Zi/M8VFFem3Mv2aTECW4edmMhkWYLDnaEE=,tag:ZDVcaMn6c8i78dF1yAmWow==,type:str]
    username: ENC[AES256_GCM,data:N0XygeQ=,iv:lZazJSRkunBYCXjDHZkd0U1KHKQr0D8gAu8ahPmikPs=,tag:tBtqqvQHE/kRbcmnjjtHrQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WWVFbFdyNk1YOEwvR2Jp
            ZGUxbGI3ZWFiNW1oc21HY1JGTllhdG5adVZVCnBvd3l2TktXbWE4NS8vQmVBV1J3
            RHI5dzlCckZSN04wdTNlNkZpNXRzeTQKLS0tIDArWVBVRytvMkpjS0VJdmdZc1VT
            ekhRQnY1YnEyT2FxQi9RdmFCQVNjZkEKe9rRv5UfbtHWeOVJVger5L76xOB5vIIT
            uN2ZY8al92nfv8o5eY9O0seqpFxfytZpxExpGsSrzdW5jqPdm2a2EA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-14T10:15:40Z"
    mac: ENC[AES256_GCM,data:uZOAKd6idVhSFOjTPMfbU11rCNa76ZyqD1+6zoX1NJ4AOo0fpbmNbxw+HSy1LW449WPAFdi2n+Tw3lggez/i4zitSNd+JR2vLn5DE5/X6s/9s9sv/yVqvUD2LPq2dcLXVgC8eWQpx9Vl718R8LUOUlUdji1bEkqJFeG/g0ORjN0=,iv:FkZQZ25rTVuk+vSEQIDLCKJtgQrVwL/Uz7gn3RVCnVk=,tag:WJC7318sCNixQHFrxiAH3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
