---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - helmrelease.yaml
  - net-attach.yaml
#  - ./netpol.yaml
  - volsync.yaml
  - volsync-local.yaml
#  - ./volsync-recs.yaml
  - pvcs.yaml
