---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: scrypted-restic
  namespace: home
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: scrypted-restic-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        annotations:
          replicator.v1.mittwald.de/replicate-to: 'volsync'
      data:
        RESTIC_REPOSITORY: '{{ .REPOSITORY_TEMPLATE }}/v1-scrypted'
        RESTIC_PASSWORD: '{{ .RESTIC_PASSWORD }}'
        AWS_ACCESS_KEY_ID: '{{ .AWS_ACCESS_KEY_ID }}'
        AWS_SECRET_ACCESS_KEY: '{{ .AWS_SECRET_ACCESS_KEY }}'
  dataFrom:
    - extract:
        key: volsync-restic-template
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: scrypted
  namespace: home
spec:
  sourcePVC: config-scrypted-0
  trigger:
    schedule: "0 7 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: scrypted-restic-secret
    cacheCapacity: 2Gi
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    cacheStorageClassName: local-path
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    retain:
      daily: 7
      within: 3d
