---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-redis
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-external-secrets-stores
    - name: cluster-apps-local-path-provisioner
    - name: cluster-apps-rook-ceph-cluster
  path: ./kubernetes/apps/database/redis/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-redis-lb
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-redis
  path: ./kubernetes/apps/database/redis/lb
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
