---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plex-trakt-sync
  namespace: media
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: plex-trakt-sync-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: plex-trakt-sync
