---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex-trakt-sync
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    image:
      repository: ghcr.io/taxel/plextraktsync
      tag: 0.27.1

    args:
      - watch

    enableServiceLinks: false

    envFrom:
      - secretRef:
          name: plex-trakt-sync-secret

    service:
      main:
        enabled: false

    ingress:
      main:
        enabled: false

    persistence:
      config:
        enabled: true
        existingClaim: plex-trakt-sync-config
        mountPath: /app/config
      config-yaml:
        enabled: true
        mountPath: /app/config/config.yml
        name: plex-trakt-sync-config-yaml
        readOnly: true
        subPath: config.yml
        type: configMap

    podAnnotations:
      configmap.reloader.stakater.com/reload: "plex-trakt-sync-config-yaml"
      secret.reloader.stakater.com/reload: "plex-trakt-sync-secret"

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
