---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - externalsecret.yaml
  - helm-release.yaml
  - config-pvc.yaml
labels:
  - pairs:
      app.kubernetes.io/name: plex-trakt-sync
      app.kubernetes.io/instance: plex-trakt-sync
configMapGenerator:
  - name: plex-trakt-sync-config-yaml
    files:
      - config/config.yml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
