---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword-connect
  namespace: security
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.security.svc.cluster.local:8080
      vaults:
        k3s-vms-flux: 1
        test-vault: 2
      auth:
        secretRef:
          connectTokenSecretRef:
            name: op-credentials
            key: token
            namespace: security
  conditions:
    # Options are namespaceSelector, or namespaces
    - namespaces:
        - "actions-runner-system"
        - "cert-manager"
        - "database"
        - "default"
        - "flux-system"
        - "home"
        - "kube-system"
        - "media"
        - "monitoring"
        - "networking"
        - "rook-ceph"
        - "security"
        - "storage"
        - "system-upgrade"
        - "trivy-system"
        - "volsync"
