---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-meta-manager-config-0
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
