---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cronjob.yaml
  - config-pvc.yaml
  - volsync.yaml
  - volsync-local.yaml
namespace: media
configMapGenerator:
  - name: plex-meta-manager-cm
    files:
      - config.yaml
generatorOptions:
  disableNameSuffixHash: true
#  annotations:
#    kustomize.toolkit.fluxcd.io/substitute: disabled
labels:
  - pairs:
      app.kubernetes.io/name: plex-meta-manager
      app.kubernetes.io/instance: plex-meta-manager
