---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-workloads-tautulli
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-workloads-rook-ceph-cluster
    - name: cluster-workloads-external-secrets-stores
    - name: cluster-workloads-volsync
  path: ./k8s/cluster-0/workloads/media/tautulli/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: tautulli
      namespace: media
  interval: 30m
  retryInterval: 1m
  timeout: 3m
