---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/bjw-s/calibre-web
      tag: 0.6.20@sha256:462de8582ffa12d5726ed781853e47b92b04ed0ec59b0772c12324dc25841977

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 65539

    enableServiceLinks: false

    env:
      TZ: "${TIMEZONE}"

    persistence:
      config:
        enabled: true
        existingClaim: calibre-web-config-0
      media:
        enabled: true
        existingClaim: media-nfs
        mountPath: /media

    service:
      main:
        ports:
          http:
            port: 8083

    ingress:
      main:
        primary: true
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNEL_ID}.cfargotunnel.com"
        hosts:
          - host: &host "calibre-web.${SECRET_DOMAIN_CASA}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: wildcard-tls
      secondary:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNEL_ID}.cfargotunnel.com"
        hosts:
          - host: &hostsecond "calibre-web.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *hostsecond

    resources:
      requests:
        cpu: 15m
        memory: 256Mi
      limits:
        memory: 512Mi
